<predefined> ::= "def evolve("<var>"):{:"<NEWLINE><code>":}"

<NEWLINE> ::= "#"
<var> ::= "v0" | "v1" | "v2" | "v3" | "v4" | "v5" | "v6"

<code> ::= <statement> | <code><statement>
<statement> ::= <stmt_list><NEWLINE> | <compound_stmt>
<compound_stmt> ::= <if>
<stmt_list> ::= <assign> | <return>

<if> ::= "if "<condition>":{:"<NEWLINE><code>":}else:{:"<NEWLINE><code>":}"
<condition> ::= <var>" "<op>" "<num>" == 1" | <var>" "<op>" "<num>" == 0"
<op> ::= "%"
<num> ::= "2"

<assign> ::= <var>" = "<var>" // 2" | <var>" = len("<var>")" | <var>" = int("<var>" / 2) - 1" | <var>" = int("<var>" / 2)" | <var>" = int(math.floor("<var>" / 2))"

<return> ::= "return "<var>"["<var>"]" | "return "<var>"["<var>" - 1:"<var>" + 1]" | "return "<var>"["<var>":"<var>" + 1]"